# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d87740a986264960f0d7174b478ce46f2c393e53a59140a68cb87cfa7f70fe05093bbc5773eba0c0bbfbbcf302b2c9e0ecb2a5fb85399f3677dca7b70b945a2

test:
  secret_key_base: a128ff4a15df6cd8ecd6426cb0587b092b8f2ccb2fb5b385b6c20d4fa3fb30e0f9209ad97b4bb2b972d93976bfcb552e3aace54bd8db546616d6bc881c2abdc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
